openapi: 3.0.3
info:
  title: Barber Booking Platform API (Phase 0 - Placeholder)
  version: 0.1.0
  description: >
    High-level outline for Phase 0 (public booking, admin calendar, mock SMS, basic analytics).
    Detailed endpoints and schemas will be produced alongside implementation and EF Core migrations.
servers:
  - url: https://api.example.com
tags:
  - name: Public
    description: Public booking flows
  - name: Admin
    description: Admin calendar and management
  - name: Analytics
    description: Basic KPIs and export
  - name: Mock
    description: Mock providers (e.g., SMS)

paths: {}

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  x-notes:
    summary: >
      This file intentionally omits concrete endpoints during early design.
      Expect resources for branches, services, staff, availability, booking holds/confirm,
      admin appointments/calendar, notifications (mock), and analytics (KPIs, CSV export).
